# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'
#' @title Eigen Matrix nanoflann nearest neighbor indexes
#' @name nanoflann_nnIndex
#' @param P dataframe (columns 1,2 being x,y) of data points.
#' @param Q dataframe (columns 1,2 being x,y) of query points.
#' @return vector of descending unqiue nearest neighbor indexes
#' @import Rcpp
#' @export
nnIndex <- function(P, Q) {
    .Call('Rcppnanoflann_nnIndex', PACKAGE = 'Rcppnanoflann', P, Q)
}

